- id: '1728245775194'
  alias: RSS NU.nl
  description: ''
  triggers:
  - trigger: event
    event_type: feedreader
    event_data:
      feed_url: https://www.nu.nl/rss/Algemeen
  conditions: []
  actions:
  - action: input_text.set_value
    metadata: {}
    data:
      value: '{{ trigger.event.data.title }}'
    target:
      entity_id: input_text.nu_nl_item_title
  - action: input_text.set_value
    metadata: {}
    data:
      value: '{{ trigger.event.data.description }}'
    target:
      entity_id: input_text.nu_nl_item_description
  - action: input_text.set_value
    metadata: {}
    data:
      value: '{{ trigger.event.data.link }}'
    target:
      entity_id: input_text.nu_nl_item_link
  mode: single
- id: '1728250536884'
  alias: AP News
  description: ''
  triggers:
  - trigger: event
    event_type: feedreader
    event_data:
      feed_url: https://openrss.org/apnews.com
  conditions: []
  actions:
  - action: input_text.set_value
    metadata: {}
    data:
      value: '{{ trigger.event.data.title }}'
    target:
      entity_id: input_text.ap_news_item_title
  - action: input_text.set_value
    metadata: {}
    data:
      value: '{{ trigger.event.data.description }}'
    target:
      entity_id: input_text.ap_news_item_description
  - action: input_text.set_value
    metadata: {}
    data:
      value: '{{ trigger.event.data.link }}'
    target:
      entity_id: input_text.ap_news_item_link
  mode: single
- id: '1765305901930'
  alias: Hue Dial Controls
  description: ''
  use_blueprint:
    path: fleeman/zigbee2mqtt-philips-hue-tap-dial-switch-by-smarthomegeeks-io.yaml
    input:
      mqtt_topic: zigbee2mqtt/Hue Dial
      tap_counter: counter.hue_dial_counter
      last_pressed: input_text.hue_dial_last_pressed_input
      button_1_single_press:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_pct: 75
        target:
          entity_id:
          - light.plafondlamp
          - light.plafondlamp_2
      - action: light.turn_off
        metadata: {}
        data: {}
        target:
          entity_id:
          - light.ikea_tradfri_living_room_lights
          - light.inbouw_spots
      button_1_double_press:
      - action: light.turn_off
        metadata: {}
        data: {}
        target:
          entity_id:
          - light.plafondlamp
          - light.plafondlamp_2
          - light.ikea_tradfri_living_room_lights
          - light.inbouw_spots
      button_1_rotate_clockwise:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_step_pct: 5
          transition: 0.5
        target:
          entity_id:
          - light.plafondlamp
          - light.plafondlamp_2
      button_1_rotate_counter_clockwise:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_step_pct: -5
          transition: 0.5
        target:
          entity_id:
          - light.plafondlamp
          - light.plafondlamp_2
      button_2_single_press:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_pct: 15
        target:
          entity_id:
          - light.ikea_tradfri_living_room_lights
      - action: light.turn_off
        metadata: {}
        data: {}
        target:
          entity_id:
          - light.plafondlamp
          - light.plafondlamp_2
          - light.inbouw_spots
      button_2_double_press:
      - action: light.turn_off
        metadata: {}
        data: {}
        target:
          entity_id:
          - light.plafondlamp
          - light.plafondlamp_2
          - light.ikea_tradfri_living_room_lights
          - light.inbouw_spots
      button_2_rotate_clockwise:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_step_pct: 5
          transition: 0.5
        target:
          entity_id:
          - light.ikea_tradfri_living_room_lights
      button_2_rotate_counter_clockwise:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_step_pct: -5
          transition: 0.5
        target:
          entity_id:
          - light.ikea_tradfri_living_room_lights
      button_3_single_press:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_pct: 15
        target:
          entity_id:
          - light.ikea_tradfri_living_room_lights
          - light.plafondlamp_2
      - action: light.turn_on
        metadata: {}
        data:
          brightness_pct: 75
        target:
          entity_id: light.inbouw_spots
      - action: light.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: light.plafondlamp
      button_3_double_press:
      - action: light.turn_off
        metadata: {}
        data: {}
        target:
          entity_id:
          - light.plafondlamp
          - light.plafondlamp_2
          - light.ikea_tradfri_living_room_lights
          - light.inbouw_spots
      button_3_rotate_clockwise:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_step_pct: 5
          transition: 0.5
        target:
          entity_id:
          - light.ikea_tradfri_living_room_lights
          - light.plafondlamp_2
          - light.inbouw_spots
      button_3_rotate_counter_clockwise:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_step_pct: -5
          transition: 0.5
        target:
          entity_id:
          - light.ikea_tradfri_living_room_lights
          - light.plafondlamp_2
          - light.inbouw_spots
      button_4_single_press:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_pct: 15
        target:
          entity_id:
          - light.ikea_tradfri_living_room_lights
          - light.plafondlamp_2
      - action: light.turn_on
        metadata: {}
        data:
          brightness_pct: 1
        target:
          entity_id: light.inbouw_spots
      - action: light.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: light.plafondlamp
      button_4_double_press:
      - action: light.turn_off
        metadata: {}
        data: {}
        target:
          entity_id:
          - light.plafondlamp
          - light.plafondlamp_2
          - light.ikea_tradfri_living_room_lights
          - light.inbouw_spots
      button_4_rotate_clockwise:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_step_pct: 5
          transition: 0.5
        target:
          entity_id:
          - light.ikea_tradfri_living_room_lights
          - light.plafondlamp_2
          - light.inbouw_spots
      button_4_rotate_counter_clockwise:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_step_pct: -5
          transition: 0.5
        target:
          entity_id:
          - light.ikea_tradfri_living_room_lights
          - light.plafondlamp_2
          - light.inbouw_spots
- id: '1766177535608'
  alias: Notify TV of dish washer program finish
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - sensor.bosch_dishwasher_operation_state
    to:
    - Finished
  conditions: []
  actions:
  - action: notify.google_tv
    metadata: {}
    data:
      title: Bosch Dish Washer
      message: Program finished
      data:
        duration: 5
        position: top-right
        fontsize: medium
        transparency: 75%
        color: teal
        interrupt: 0
  mode: single
- id: '1766255061066'
  alias: Washer Monitor
  description: ''
  use_blueprint:
    path: leofabri/appliance-status-monitor.yaml
    input:
      appliance_socket: switch.0xa4c13807383bffff
      appliance_power_sensor: sensor.0xa4c13807383bffff_power
      appliance_finishing_power_threshold: 2
      appliance_job_cycle: input_boolean.washing_machine_job_cycle
      delayed_job_completion_timer: timer.washing_machine_delayed_job_completion_timer
      automation_self_trigger: input_boolean.washing_machine_automation_self_trigger
      delayed_job_completion_duration: 15
      appliance_state_machine: input_select.washing_machine_state_machine
      appliance_starting_power_threshold: 10
      actions_job_cycle_ends:
      - action: notify.mobile_app_iphone_van_wouter
        metadata: {}
        data:
          title: Bosch Washing Machine
          message: Program finished
      - action: notify.google_tv
        metadata: {}
        data:
          message: Program finished
          data:
            duration: 5
            position: top-right
            fontsize: medium
            transparency: 75%
            color: teal
            interrupt: 0
          title: Bosch Washing Machine
- id: '1766255061080'
  alias: Good Morning - generate episode
  description: Pulls today's weather and starts podcast generation
  trigger:
    - platform: time
      at: "05:45:00"
  condition: []
  action:
    - action: weather.get_forecasts
      target:
        entity_id: weather.home
      data:
        type: daily
      response_variable: forecast_response
  
    - variables:
        today_forecast: "{{ forecast_response['weather.home'].forecast[0] }}"
        payload: >-
          {{
            {
              "source_facts": {
                "episode_date": now().strftime("%Y-%m-%d"),
                "location": "Utrecht, Netherlands",
                "weather": {
                  "summary": (today_forecast.condition | replace('-', ' ') ~ ", highs near "
                              ~ today_forecast.temperature | round(0) | string ~ "°C") ,
                  "high_c": today_forecast.temperature,
                  "low_c": today_forecast.templow,
                  "conditions": today_forecast.condition,
                  "precipitation_chance": today_forecast.precipitation_probability,
                  "wind_kph": today_forecast.wind_speed
                },
                "calendar_events": [],
                "reminders": [],
                "interests": ["technology", "world"]
              }
            } | to_json
          }}
  
    - action: rest_command.goodmorning_generate_episode
      data:
        payload: "{{ payload }}"